apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/

patches:
- patch: |
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: ingress-address-pool
      namespace: metallb-system
    spec:
      addresses:
      - 10.30.8.91/32
