apiVersion: v1
kind: Service
metadata:
  name: router-internal-default-ext
  namespace: openshift-ingress
  annotations:
    metallb.universe.tf/address-pool: ingress-address-pool
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  - name: metrics
    port: 1936
    targetPort: metrics
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
  type: LoadBalancer
